### ISSUE TITLE
PhotoQt icon covers file index in top-left corner

### ISSUE THREAD

**Issue by muzso** [luspi/photoqt-dev#50] opened 2015-05-17 13:12 UTC
Using v1.2 the PhotoQt icon covers the current file index in the top-left corner when in fullscreen mode. Here's a screenshot of what I mean:
![screenshot from 2015-05-17 15 09 10](https://cloud.githubusercontent.com/assets/12482925/7670485/ce2f2210-fca6-11e4-9a1f-3f7a89b8442b.png)

Only the total image count is visible, the current image index is not (or at least it's not really readable).

(I didn't see this issue among the known problems of v1.2 and I didn't see this among old (closed or still open) issues here on GitHub either.)

I'm using Photoqt from Sam's PPA. The exact package version is 1.2~trusty~ppa1 (amd64).
The OS is Ubuntu 14.04.2.

**Comment by luspi** [comment] 2015-05-17 18:56
Thanks for reporting @muzso 
The icon you can see is actually the system tray icon. Unfortunately this is not a bug of PhotoQt, but a known bug involving Qt/Unity, that apparently will be fixed with Qt version 5.5 and it seems that Ubuntu added their own fix for this in Ubuntu 15.04. However, afaik, it unfortunately wont be backported to 14.04 and 14.04 still seems to rely on Qt 5.2.1. So to fix this, you would either have to update the default Qt version (once Qt 5.5 is released, should be happening this month according to what I read) or update you Ubuntu installation...

You can read more about this bug in the Qt bug tracker here:
https://bugreports.qt.io/browse/QTBUG-31762

**Comment by muzso** [comment] 2015-05-17 20:57
I find this a bit strange. I've "TrayIcon=0" in the "[Behaviour]" section in my settings file. Why is there any tray icon then? :-o

**Comment by luspi** [comment] 2015-05-17 21:35
Exactly. It used to be the case that "TrayIcon=0" completely disabled the tray icon, but since v0.8 or v0.9 this changed to the "Hide to tray" action... However, it actually might not be a bad idea to have an option to disable it completely. Let me have a quick look...

**Comment by luspi** [comment] 2015-05-17 22:24
Okay, I just added an option to do exactly that, completely disable the tray icon: 44b172ddc99b9447d1abf3912adb4af0cfdfd74b

**Comment by luspi** [comment] 2015-05-17 23:51
And now this change also made it into the QML port: efb7a9cf7e4d6f841b4874a03afdbb10e9da2537 and 086bbb3f06c3750b61ab1c06bf275d70d15e67e6

**Comment by luspi** [comment] 2015-05-17 23:52
And now this change also made it into the QML port: luspi@efb7a9cf7e4d6f841b4874a03afdbb10e9da2537 and luspi@086bbb3f06c3750b61ab1c06bf275d70d15e67e6

**Comment by luspi** [comment] 2015-06-15 14:00
PhotoQt is moving away from GitHub to GitLab ([more info](http://photoqt.org/news/1434375887)). This issue is duplicated here: https://gitlab.com/luspi/photoqt-legacy/issues

**Comment by muzso** [comment] 2015-06-16 06:17
The change just got into the samrog131 repo with 1.2.1 and works perfectly. Thanks!
However the new trayicon mode's (TrayIcon=2) label in settings says "Show tray icon, but don't hide to it". If I didn't knew this was the new trayicon mode, I wouldn't have guessed that it'd remove the trayicon (in Gnome / Ubuntu) completely. :-o

**Comment by luspi** [comment] 2015-06-18 10:45
Well, actually, a value of 2 is what was previously the value of 0... In v1.2.1 and later versions, a value of 0=no trayicon, 1=full trayicon, 2=visible trayicon but no functions...

**Comment by luspi** [comment] 2015-06-18 10:46
Oh, shoot, just tested it and you're right, the values of 0 and 2 are mixed up in v1.2.1 :/ However, it's already working properly in v1.3beta!

**Comment by luspi** [comment] 2015-07-27 02:39
It should all work fine now with v1.3...

**Closed by luspi** 2015-07-27 02:39 UTC
