### ISSUE TITLE
Tearing when panning zoomed images

### ISSUE THREAD

**Issue by M4he** [luspi/photoqt-dev#46] opened 2015-03-13 10:48 UTC
Whenever I zoom in an image so that its displayed size exceeds the screen and pan it from left to right, I get tearing.
I'm on Kubuntu 14.04 KDE, have VSync and TripleBuffer enabled on my system. No other viewer (e.g. GwenView) shows any tearing when doing that. In general, I don't have tearing anywhere else on the desktop.

**Comment by luspi** [comment] 2015-03-22 05:00
(Sorry for not replying earlier!)

Hm, this is an odd issue, as I make use of standard elements provided by Qt (which other Qt image viewers like GwenView) are also based on... I'll see if I can reproduce it when running Kubuntu in VirtualBox.

**Comment by M4he** [comment] 2015-03-22 09:59
Thanks for looking into it!
I found it best reproducable with very large images (e.g. 4000x2000 on a 1366x768 screen) by hitting '1' to display the image in 1:1 size and then using the mouse to pan it from left to right repeatedly.

By the way, it is independent of hardware as it seems. Reproducable on Intel HD 4000 (iGPU) running on Mint 17.1 KDE as well as with Nvidia GTX 660 running on Kubuntu 14.04.1.

I wonder if reproducibility with VirtualBox is viable in regards of graphics since there are some additional graphics layers applied to the display output. I wonder if VirtualBox's virtual display will sync to VBlank the same way the guest system's compositor would do running natively on the hardware. Speaking of it, in most cases your host system will also have a compositing mechanism applied on top of the VirtualBox output which might falsify the results.
I could imagine that in VirtualBox you get either 1) always tearing due to inaccurate VBlank syncing of VirtualBox or 2) never tearing due to 'fake' VSync from the host system's compositing.

Anyway, I think it's best to tackle this using a natively running system. If you have a system with an integrated Intel graphics available, you can boot a live image and play around there since the Intel drivers are open ones and already included and loaded at startup.
Either way, don't forget to set KDE's VSync to 'full screen redraws' though! (System Settings > Desktop Effects > Advanced)

Odd that it happens even though you are using native Qt elements. Maybe it's some simple sync to VBlank flag that has to be set for those elements, I don't know...


(Sorry for the wall of text >.<)

**Comment by luspi** [comment] 2015-03-25 00:32
Thanks for the comments!

I'll probably do exactly that, running a Live System. I'm afraid though, I wont be able to do it before mid April as I'm currently in the final stretch of the winter semester in university and am swamped with work...

But I'll let you know what I can figure out asap!!

**Comment by M4he** [comment] 2015-03-25 09:39
It's only a cosmetic issue, take your time.

**Comment by luspi** [comment] 2015-05-18 23:49
Okay, I haven't been very talkative about this problem, however, I've not forgotten about it. I actually was perfectly able to reproduce the issue with the tearing.
I wont be "fixing" this issue though (hear me out), as it doesn't seem to occur anymore using the QML items. I guess this is because the QML elements use a different underlying code basis and thus do things a little different... So you wont see the fix in the bug fix release 1.2.1, but it should be fixed in the QML port (which will be released as 1.3). Currently, the plan is to release v1.2.1 and v1.3BETA at the same time. That will probably happen in about a month's time (rough guestimate, can't actually tell for sure at the moment...)

**Comment by luspi** [comment] 2015-06-15 14:00
PhotoQt is moving away from GitHub to GitLab ([more info](http://photoqt.org/news/1434375887)). This issue is duplicated here: https://gitlab.com/luspi/photoqt-legacy/issues

**Comment by luspi** [comment] 2015-07-27 02:38
Seems to be working now with v1.3. Closing this.

If you have further comments, please use: https://gitlab.com/luspi/photoqt-legacy/issues/6

**Closed by luspi** 2015-07-27 02:38 UTC
